name: work_record_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stop_watch_timer: ^2.0.0
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
